spring:
  data:
    mongodb:
      host: 139.165.56.93
      port: 27017
      database: test
      option:
        max-connection-idle-time: 1500
        max-connection-per-host: 200
        max-wait-time: 60000
        max-connection-life-time: 0
        connect-timeout: 10000
        socket-timeout: 60000
      password: '123456'
      username: root
      authentication-database: admin